api_platform:
    collection:
        order_parameter_name: order
        pagination:
            items_per_page: 5
            maximum_items_per_page: 40
            client_enabled: true
            enabled_parameter_name: pagination
            client_items_per_page: true
            items_per_page_parameter_name: limit
    swagger:
        api_keys:
           apiKey:
              name: X-AUTH-TOKEN
              type: header
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
