easy_admin:
    design:
        brand_color: 'red'
    site_name: 'Labstag'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
      user:
        class: App\Entity\User
        label: 'Utilisateurs'
        form:
          fields:
            - username
            - { property: apikey, type: "text" }
        new:
          title: "Ajout d'un utilisateur"
        edit:
          title: "Edition d'un utilisateur"
