easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@VichUploader/Form/fields.html.twig'
      - 'easyadmin/fields.html.twig'
    brand_color: "red"
    menu:
      - label: "Dashboard"
        icon: dashboard
        route: easyadmin_dashboard
        parameters: { menuIndex: 0 }
        default: true
      - { role: ROLE_SUPER_ADMIN, entity: 'User', icon: 'user' }
      - { role: ROLE_SUPER_ADMIN, entity: 'Configuration', icon: 'gear' }
  site_name: "Labstag"
  formats:
    date: "d/m/Y"
    time: "H:i"
    datetime: "d/m/Y H:i:s"
  entities:
    Configuration:
      class: App\Entity\Configuration
      label: "Configuration"
      role: ROLE_SUPER_ADMIN
      list:
        sort: 'name'
        title: "Configuration"
        actions:
          - { name: 'new', label: 'Ajouter', icon: 'add' }
          - { name: 'edit', label: 'Éditer', icon: 'edit' }
          - { name: 'delete', label: 'Supprimer', icon: 'trash' }
    User:
      class: App\Entity\User
      label: "Utilisateurs"
      role: ROLE_SUPER_ADMIN
      search:
        sort: 'username'
      list:
        actions:
          - { name: 'new', label: 'Ajouter', icon: 'add' }
          - { name: 'edit', label: 'Éditer', icon: 'edit' }
          - { name: 'delete', label: 'Supprimer', icon: 'trash' }
        sort: 'username'
        title: 'Utilisateurs'
        fields:
          - { property: 'avatar', type: 'image', base_path: '%app.path.files%avatar', template: 'easyadmin/uploadimg.html.twig' }
          - username
          - email
          - apikey
          - enable
          - {
              property: "features",
              type: "raw",
              label: "Se connecter",
              template: "easyadmin/user/connexion.html.twig",
              role: ROLE_ALLOWED_TO_SWITCH,
            }
      form:
        fields:
          - username
          - email
          - { property: apikey, type: "text", label: "API KEY" }
          - { property: 'imageFile', type: 'vich_image' }
          - {
              property: plainPassword,
              type: "repeated",
              type_options:
                {
                  type: Symfony\Component\Form\Extension\Core\Type\PasswordType,
                  first_options: { label: "Mot de passe" },
                  second_options: { label: "Confirmation mot de passe" },
                  required: false,
                },
            }
      new:
        title: "Ajout d'un utilisateur"
      edit:
        title: "Edition d'un utilisateur"
