easy_admin:
    disabled_actions: ["show"]
    user:
        avatar_property_path: "avatar"
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@VichUploader/Form/fields.html.twig"
            - "easyadmin/fields.html.twig"
        brand_color: "red"
        menu:
            - {
                  label: "Dashboard",
                  icon: dashboard,
                  route: easyadmin_dashboard,
                  parameters: { menuIndex: 0 },
                  default: true,
              }
            - {
                  label: "Weblog",
                  children:
                      [
                          { entity: "Post", icon: "user" },
                          { entity: "Category", icon: "inbox" },
                          { entity: "Tags", icon: "tags" },
                      ],
              }
            - { role: ROLE_SUPER_ADMIN, entity: "User", icon: "user" }
            - { role: ROLE_SUPER_ADMIN, entity: "Configuration", icon: "gear" }
    site_name: "Labstag"
    formats:
        date: "d/m/Y"
        time: "H:i"
        datetime: "d/m/Y H:i:s"
    entities:
        Post:
            class: App\Entity\Post
            help: "Gestion des articles du site"
            label: "Articles"
            edit:
                title: "Modifier l'article"
            list:
                title: "Articles"
                sort: "createdAt"
                actions:
                    - { name: "new", label: "Ajouter", icon: "add" }
                    - { name: "edit", label: "Éditer", icon: "edit" }
                    - { name: "delete", label: "Supprimer", icon: "trash" }
                fields:
                    - {
                          property: "image",
                          type: "vich_file",
                          base_path: "%app.path.files%post",
                          template: "easyadmin/uploadimg.html.twig",
                      }
                    - name
                    - refuser
                    - enable
                    - refcategory
                    - tags
            form:
                fields:
                    - name
                    - slug
                    - refcategory
                    - tags
                    - refuser
                    - { property: "content", type: "fos_ckeditor" }
                    - { property: "imageFile", type: "vich_image" }
        Tags:
            class: App\Entity\Tags
            help: "Gestion des tags"
            label: "Tags"
            edit:
                title: "Modifier le tags"
            list:
                title: "Tags"
                actions:
                    - { name: "new", label: "Ajouter", icon: "add" }
                    - { name: "edit", label: "Éditer", icon: "edit" }
                    - { name: "delete", label: "Supprimer", icon: "trash" }
                sort: "name"
                fields:
                    - name
                    - slug
                    - posts
            form:
                fields:
                    - name
                    - slug
        Category:
            class: App\Entity\Category
            help: "Gestion des catégories"
            label: "Catégories"
            edit:
                title: "Modifier la categorie"
            list:
                title: "Catégories"
                actions:
                    - { name: "new", label: "Ajouter", icon: "add" }
                    - { name: "edit", label: "Éditer", icon: "edit" }
                    - { name: "delete", label: "Supprimer", icon: "trash" }
                sort: "name"
                fields:
                    - name
                    - slug
                    - posts
            form:
                fields:
                    - name
                    - slug
        Configuration:
            class: App\Entity\Configuration
            help: "Gestion de la configuration du site"
            label: "Configuration"
            role: ROLE_SUPER_ADMIN
            edit:
                title: "Modifier la configuration"
            list:
                sort: "name"
                title: "Configuration"
                actions:
                    - { name: "new", label: "Ajouter", icon: "add" }
                    - { name: "edit", label: "Éditer", icon: "edit" }
                    - { name: "delete", label: "Supprimer", icon: "trash" }
        User:
            class: App\Entity\User
            help: "Gestion des utilisateurs"
            label: "Utilisateurs"
            role: ROLE_SUPER_ADMIN
            edit:
                title: "Modifier l'utilisateur"
            search:
                sort: "username"
            list:
                actions:
                    - { name: "new", label: "Ajouter", icon: "add" }
                    - { name: "edit", label: "Éditer", icon: "edit" }
                    - { name: "delete", label: "Supprimer", icon: "trash" }
                sort: "username"
                title: "Utilisateurs"
                fields:
                    - {
                          property: "avatar",
                          type: "vich_file",
                          base_path: "%app.path.files%avatar",
                          template: "easyadmin/uploadimg.html.twig",
                      }
                    - username
                    - email
                    - apikey
                    - enable
                    - {
                          property: "features",
                          type: "raw",
                          label: "Se connecter",
                          template: "easyadmin/user/connexion.html.twig",
                          role: ROLE_ALLOWED_TO_SWITCH,
                      }
            form:
                fields:
                    - username
                    - email
                    - { property: apikey, type: "text", label: "API KEY" }
                    - { property: "imageFile", type: "vich_image" }
                    - {
                          property: plainPassword,
                          type: "repeated",
                          type_options:
                              {
                                  type: Symfony\Component\Form\Extension\Core\Type\PasswordType,
                                  first_options: { label: "Mot de passe" },
                                  second_options:
                                      { label: "Confirmation mot de passe" },
                                  required: false,
                              },
                      }
