knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        microsoft_main:
            # this will be one of the supported types
            type: microsoft
            client_id: '%env(OAUTH_MICROSOFT_ID)%'
            client_secret: '%env(OAUTH_MICROSOFT_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_microsoft_check
            redirect_params: {}
        facebook_main:
            # this will be one of the supported types
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v2.12

        gitlab_main:
            # this will be one of the supported types
            type: gitlab
            client_id: '%env(OAUTH_GITLAB_ID)%'
            client_secret: '%env(OAUTH_GITLAB_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_gitlab_check
            redirect_params: {}
            
        google_main:
            # this will be one of the supported types
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_google_check
            redirect_params: {}
        github_main:
            # this will be one of the supported types
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_github_check
            redirect_params: {}
        bitbucket_main:
            # this will be one of the supported types
            type: bitbucket
            client_id: '%env(OAUTH_BITBUCKET_ID)%'
            client_secret: '%env(OAUTH_BITBUCKET_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_bitbucket_check
            redirect_params: {}
        discord_main:
            # this will be one of the supported types
            type: discord
            client_id: '%env(OAUTH_DISCORD_ID)%'
            client_secret: '%env(OAUTH_DISCORD_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_discord_check
            redirect_params: {}

