vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        upload_file:
            uri_prefix: "%app.path.files%"
            upload_destination: "%kernel.project_dir%/public%app.path.files%"
            namer: vich_uploader.namer_uniqid
