version: '3.4'

networks:
    net:
        driver: overlay
        attachable: true

volumes:
    mariadb:
        driver: local

services:
    mariadb:
        image: mariadb:10.5.1
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: core
            MYSQL_USER: labstag
            MYSQL_PASSWORD: password
            TZ: Europe/Paris
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        networks:
            - net
    apache:
        image: httpd
        volumes:
            - ${PWD}/apps:/usr/local/apache2/htdocs/
            - ${PWD}/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
            - 80:80
        networks:
            - net
    phpfpm:
        image: koromerzhin/phpfpm:7.4
        volumes:
            - ${PWD}/apps:/usr/local/apache2/htdocs
            - ${PWD}/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - net
