version: '3.4'
services:
    labstag-mariadb:
        image: mariadb:10.4.12
        container_name: labstag-mariadb
        restart: 'no'
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: core
            MYSQL_USER: labstag
            MYSQL_PASSWORD: password
            TZ: Europe/Paris
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - labstag-network
    labstag-aphp7:
        depends_on:
            - labstag-phpfpm7
            - labstag-mariadb
        build: docker/aphp7
        container_name: labstag-aphp7
        restart: 'no'
        volumes:
            - ${PWD}/apps:/usr/local/apache2/htdocs/
        ports:
            - 8087:80
        links:
            - labstag-phpfpm7:phpfpm
            - labstag-mariadb:mariadb
        networks:
            - labstag-network
    labstag-phpfpm7:
        depends_on:
            - labstag-mariadb
        image: koromerzhin/phpfpm:7.4
        container_name: labstag-phpfpm7
        restart: 'no'
        volumes:
            - ${PWD}/apps:/usr/local/apache2/htdocs
        links:
            - labstag-mariadb:mariadb
        networks:
            - labstag-network
networks:
    labstag-network:
        driver: bridge

volumes:
    mariadb:
        driver: local
