version: "3.4"
services:
  labstag-db:
    image: mariadb:10.3.20
    container_name: labstag-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: core
      MYSQL_USER: labstag
      MYSQL_PASSWORD: "password"
    ports:
      - 3307:3306
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
  labstag-aphp7:
    depends_on:
      - labstag-phpfpm7
      - labstag-db
    image: httpd
    container_name: labstag-aphp7
    restart: always
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
      - ${PWD}/docker/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8087:80
    links:
      - labstag-phpfpm7:phpfpm
      - labstag-db:db
  labstag-phpfpm7:
    depends_on:
      - labstag-db
    build: docker/phpfpm7
    container_name: labstag-php7
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs
    links:
      - labstag-db:db
