resources:
  Labstag\Entity\User:
    itemOperations:
      get: ~
      put: ~
      delete: ~
      check:
        route_name: "api_checkuser"
        swagger_context:
          summary: "Verifie si l'utilisateur est présent dans la base de données"
          parameters:
            -
              name: username
              in: query
