<<<<<<< HEAD
api_platform:
    resource: .
    type: api_platform
    prefix: /api
=======
api_platform:
    resource: .
    type: api_platform
    prefix: /api
>>>>>>> 70eef9d9de7dd17df3a3addf58c7c49623b0f58b
