name: Test suite

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: "7.4"
          extensions: intl, mbstring, bcmath, zip, gd, ldap, soap

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: make Install

      - name: Run the test suite
        run: |
          make start
          make phpunit
