name: 'Test suite'
on:
    - push
jobs:
    makefile:
        runs-on: ubuntu-latest
        steps:
            - {name: Checkout, uses: actions/checkout@v2}
            - {name: 'Docker swarm init', run: 'docker swarm init --default-addr-pool 10.20.0.0/16'}
            - {name: 'Create proxy network', run: 'make create-network'}
            - {name: 'Show HELP', run: 'make help'}
            - {name: 'Build containers', run: 'make deploy'}
            - {name: 'Check running stack', run: 'docker stack ls'}
            - {name: 'Set env', run: 'make setenv'}
            - {name: Sleep, uses: jakejarvis/wait-action@master, with: {time: 1m}}
            - {name: 'Check running containers', run: 'docker service ls'}
            - {name: 'Composer install', run: 'make composer-install'}
            - {name: 'BDD MIGRATE', run: 'make migrate'}
            - {name: 'Run the fixtures', run: 'make fixtures'}
            - {name: 'Run the test suite', run: 'make phpunit'}
