name: Test suite

on: [push]

jobs:
  makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show HELP
        run: make help

      - name: Show HELP
        run: make
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: make install

      - name: Validate composer.json and composer.lock
        run: |
          make start
          make composer-validate

      - name: Run the test suite
        run: |
          make start
          make phpunit
