name: Test suite

on: [push]

jobs:
  makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show HELP
        run: make help

      - name: Show HELP
        run: make
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build containers
        run: make build

      - name: Start containers
        run: make start

      - name: Check running containers
        run: docker ps -a

      - name: Composer install
        run: make composer-install

      - name: NPM install
        run: npm install

      - name: Validate composer
        run: make composer-validate
			
			- name: Install BDD
				run: make bdd-dev

      - name: Add database
        run: make migrate

      - name: Run the test suite
        run: |
          make phpunit
