name: Test suite
on: [push]
jobs:
    makefile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Docker swarm init
              run: docker swarm init --default-addr-pool 10.20.0.0/16
            - name: Show HELP
              run: make help
            - name: Show HELP
              run: make
            - name: Build containers
              run: make deploy
            - name: Check running containers
              run: docker ps -a
            - name: Composer install
              run: make composer-install-dev
            - name: NPM install
              run: make npm-install-dev
            - name: Install BDD
              run: make bdd-dev
            - name: Add database
              run: make migrate
            - name: Run the fixtures
              run: make fixtures
            - name: Run the test suite
              run: make phpunit
            - name: Create assets
              run: make create-asset
