name: Test suite
on: [push]
jobs:
    makefile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Show HELP
              run: make help
            - name: Show HELP
              run: make
            - uses: actions/upload-artifact@v1
              with:
                  name: makefile
                  path: makefile
    launch:
        needs: makefile
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v1
              with:
                  name: makefile
            - name: Build containers
              run: make build
            - name: Start containers
              run: make start
            - name: Check running containers
              run: docker ps -a
    stacks:
        needs: launch
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build containers
              run: make build
            - name: Start containers
              run: make start
            - name: Composer install
              run: make composer-install-dev
            - name: NPM doctor
              run: make npm-doctor
            - name: NPM install
              run: make npm-install
    database:
        needs: stacks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build containers
              run: make build
            - name: Start containers
              run: make start
            - name: NPM install
              run: make npm-install
            - name: Install BDD
              run: make bdd-dev
            - name: Add database
              run: make migrate
            - name: Run the fixtures
              run: make fixtures
            - name: Run the test suite
              run: make phpunit
