name: Test suite

on: [push]

jobs:
  makefile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Show HELP
        run: make help

      - name: Show HELP
        run: make
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build docker
        run: make build

      - name: Start Docker
        run: make start

      - name: Check running containers
        run: docker ps -a

      - name: Composer install
        run: make composer-install

      - name: NPM install
        run: npm install

      - name: Validate composer.json and composer.lock
        run: |
          make composer-validate

      - name: Run the test suite
        run: |
          make phpunit
